install:
#  - set QTDIR=C:\Qt\5.5\msvc2013_64
  - set QTDIR=C:\Qt\5.5\mingw492_32
  - set PATH=%PATH%;%QTDIR%\bin
  - set PATH=%PATH%;C:\MinGW\bin
  - set PATH=%PATH%;C:\Qt\Tools\mingw492_32
  - git submodule init
  - git submodule update --depth 1 3rdparty\windows
build_script:
  - cd quick
  - qmake -spec win32-g++
  - qmake -r
  - mingw32-make
